# Generated by Django 6.0.6 on 2026-09-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_landingimages_category_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingimages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landing_images', to='main.category'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='main.category'),
        ),
    ]
